name: Build

on:

  # push:
  #   branches:
  #     - main

  workflow_call:
    secrets:
      DOCKER_REGISTRY_USER:
        required: true
    
jobs:

  build:
    runs-on: [build,linux64]
    container: 
      image: fr-qafactorydev.europe.altair.com/build-linux64:mpi-2021.2.0
      credentials: 
        username: ${{secrets.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
      volumes: 
        - /etc/localtime:/etc/localtime:ro

    strategy:
      matrix:
        include:
          - build_number: build1
          # - build_number: build2
          # - build_number: build3
          # - build_number: build4
    steps:
    
    # Set the working dir suffixed with branch name
    - uses: haya14busa/action-cond@v1
      id: condval
      with:
        cond: ${{ github.base_ref == '' }}
        if_true: ${{github.ref_name}}
        if_false: ${{github.base_ref}}
    - name: Use conditional value
      run: |
        echo "working-directory=${{ steps.condval.outputs.value }}" >> $GITHUB_ENV
        ls -l $GITHUB_ENV
        cat $GITHUB_ENV        
    - name: Create branch oriented WS directory
      run: |
        mkdir -p ${{env.working-directory}}

    - name: Clean local exe dir
      working-directory: ${{env.working-directory}}
      run: |
        rm -rf exec

    # Get last git modifications, don't clean before (way to keep persistent obj files)
    - uses: actions/checkout@v2
      with:
        path: ${{env.working-directory}}
        clean: 'false'
        