name: Main CI

on:

  push:
    branches:
      - main

jobs:

  job1:
    runs-on: [common,linux64]
    container: 
      image: fr-qafactorydev.europe.altair.com/common-linux64
      credentials: 
        username: ${{secrets.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
      volumes: 
         - /etc/localtime:/etc/localtime:ro

    steps:
      # Set the working dir suffixed with branch name
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ github.base_ref == '' }}
          if_true: ${{github.ref_name}}
          if_false: ${{github.base_ref}}
      - name: Use conditional value
        run: |
          echo "working-directory=${{ steps.condval.outputs.value }}" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Run 1
        run: |
          export MADATE=`date`;
          echo "run job 1 at ${MADATE} (WS is ${{env.working-directory}})"

  job2:
    needs: job1
    runs-on: [common,linux64]
    container: 
      image: fr-qafactorydev.europe.altair.com/common-linux64
      credentials: 
        username: ${{secrets.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
      volumes: 
         - /etc/localtime:/etc/localtime:ro

    steps:
      - name: Run 2
        run: |
          export MADATE=`date`;
          echo "run job 2 at ${MADATE} (WS is ${{job1.steps.condval.outputs.value}})"
  # call_workflow_build:
  #   uses: ./.github/workflows/build-ci.yml
  #   secrets:
  #     DOCKER_REGISTRY_USER: ${{secrets.DOCKER_REGISTRY_USER}}
  #     DOCKER_REGISTRY_PASSWD: ${{secrets.DOCKER_REGISTRY_PASSWD}}



  # call_workflow_sync:
  #   needs: call_workflow_build
  #   uses: ./.github/workflows/sync.yml
  #   with:
  #     working_directory: "LALALa"
  #   secrets:
  #     DOCKER_REGISTRY_USER: ${{secrets.DOCKER_REGISTRY_USER}}
  #     DOCKER_REGISTRY_PASSWD: ${{secrets.DOCKER_REGISTRY_PASSWD}}

