name: Main CI

on:

  push:
    branches:
      - main

jobs:

  call_workflow_build:
    uses: ./.github/workflows/build-ci.yml
    secrets:
      DOCKER_REGISTRY_USER: ${{secrets.DOCKER_REGISTRY_USER}}
      DOCKER_REGISTRY_PASSWD: ${{secrets.DOCKER_REGISTRY_PASSWD}}


